version: '3.6'
  
services:
  spring-boot-docker:
    build: .
    ports:
      - 8081:8081
    environment:
      - example=my value  
    volumes:
      - javatmp:/tmp
    network_mode: host         
