server:
  port: 8082
  
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/docker_db
#    username: "root"
#    password: "root"
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#  application:
#    name: giftu

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: "admin"
    password: ""
  h2:
    console:
      enabled: true
      path: /h2

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp